### ISSUE TITLE
Copied text on hover

### ISSUE THREAD

**Issue by splitt3r** [flathub/linux-store-frontend#105]
@antoniorsz the `Copied` text pops up while simply hovering the text without pressing the copy button.

![copy](https://user-images.githubusercontent.com/1869584/39998318-02f16df4-5786-11e8-9607-4a5fb89f374b.png)

**Comment by jgarciao** [comment]
I added that. Thanks for discovering it!

El dl., 14 de maig 2018, 14:51, Kai Schröer <notifications@github.com> va
escriure:

**Comment by antoniorsz** [comment]
I'll try to fix this today.

**Comment by jgarciao** [comment]
Maybe adding matTooltipDisabled will fix it, but I don't know if
tooltip.show() will work with that

https://material.angular.io/components/tooltip/overview



El dl., 14 de maig 2018, 18:03, antoniorsz <notifications@github.com> va
escriure:
