### ISSUE TITLE
this.config is null

### ISSUE THREAD

**Issue by splitt3r** [flathub/linux-store-frontend#106]
Seems to be related to the gallery component. It happens on both the Angular 5 and Angular 6 version of the page.

Perhaps sth. arround:

https://github.com/MurhafSousli/ngx-gallery/blob/7838e9c979558ad7e0721d6435aab221a477e1fb/src/app/gallery/core/services/gallery.service.ts#L18

Screenshot:

![config](https://user-images.githubusercontent.com/1869584/39998780-716acb30-5787-11e8-815b-bb7f86b85589.png)

**Comment by jgarciao** [comment]
I think this and many other issues related to the screenshots will be fixed
updating the component to the latest version.

From 1.x to 2.x they changed the name (now is ngx-gallery) and some of the
data structures but it should't be too difficult to upgrade it.

https://www.npmjs.com/package/ngx-gallery

I personally would like to do something else this week. Are you interested?

El dl., 14 de maig 2018, 15:01, Kai Schröer <notifications@github.com> va
escriure:

**Comment by splitt3r** [comment]
Ok. I will have a look at it.

**Comment by jgarciao** [comment]
Thanks!

El dl., 14 de maig 2018, 17:44, Kai Schröer <notifications@github.com> va
escriure:
