### ISSUE TITLE
[flathub/builds] Hover effect on app id makes difficult to click it

### ISSUE THREAD

**Issue by somas95** [flathub/linux-store-frontend#112]
A gif will explain this better:
![peek 2018-05-18 21-31](https://user-images.githubusercontent.com/8913975/40254220-e59d6bbc-5ae2-11e8-96ee-e262d402283d.gif)

Not sure if this is the place to report this

**Comment by jgarciao** [comment]
I think this should be reported to the [Buildbot software](http://buildbot.net/) (preferred) or to our [instance of buildbot](https://github.com/flathub/buildbot-config/issues)
