### ISSUE TITLE
Improve flathub.org SEO (Search Engine Optimization)

### ISSUE THREAD

**Issue by jgarciao** [flathub/linux-store-frontend#118]
Improve the website metadata:
- [X] Add title and description on every page #7 
- [X] Refactor the code to create an Angular SeoService that does titles, descriptions and other social media tags [like in this example](https://stackoverflow.com/questions/11616697/how-to-use-the-og-open-graph-meta-tag-for-facebook-share)

Analyze and improve how the website is being crawled by Google:
- [X] Add flathub.org to Google Search Console
- [X] Check how flathub.org is doing in Google Search Console
  - Is doing very bad at this time (v 0.6.5) because of being a SPA website. Only the homepage is detected and Googlebot can't render it properly

Stuff I'm already working on:
- [X] Create a sitemap and register it in Google Search Console
- [X] Prerender the website for search engines and bots using the pretender.io service
- [X] Change nginx configuration to serve prerendered content to search engines and bots

**Comment by antoniorsz** [comment]
I too started working on this, but with https://angular.io/guide/universal
You can check my progress on: https://github.com/antoniorsz/linux-store-frontend/tree/universal
There are two basic ways we can go with this:
1. Prerender everything after every pull from repo and keep using nginx.
2. Stop using nginx and prerender everything as we go with express.

Either of this options I haven't really tested yet on a prod like environment (with https and such)
Let me know if you think I should stop pursuing this.

**Comment by jgarciao** [comment]
Sorry, I have to clean the issue list and update the code on master (there are many things that are in the 0.6.x branch, which is the one in production)

About the SEO stuff, @ramcq and me managed to get the prerender service working and the main search engines are now indexing the content properly

Google, for example, is indexing more than 500 pages now at flathub.org
https://www.google.com/search?nomo=1&hl=ca-US&q=site:flathub.org

**Comment by jgarciao** [comment]
>Let me know if you think I should stop pursuing this.

Thanks a lot for contributing but for now I think the solution we found works fine enough not to go to the universal way
