### ISSUE TITLE
Localise app information page

### ISSUE THREAD

**Issue by nedrichards** [flathub/linux-store-frontend#121]
Appdata files often include translations and locale specific information. We need to make sure that we're serving translated information where possible (and not serving it incorrectly)

e.g. the [endless photos app](https://flathub.org/apps/details/com.endlessm.photos) currently shows too many screenshots. The appdata specifies per language screenshots so for english we should only pick one.

```
    <screenshot>
      <image type="source" xml:lang="es">https://raw.githubusercontent.com/endlessm/eos-photos/master/data/assets/screenshot1-es.png</image>
      <image type="source" xml:lang="pt">https://raw.githubusercontent.com/endlessm/eos-photos/master/data/assets/screenshot1-pt.png</image>
      <image type="source">https://raw.githubusercontent.com/endlessm/eos-photos/master/data/assets/screenshot1-C.png</image>
</screenshot>
```

**Comment by rshuler** [comment]
@nedrichards As I commented on the eos-photos issue, I think the problem is in the appstream for this app on flathub.  I suspect that the per-language screenshots you mention above are from the older version of the app on our eos-apps repo, and somehow that did not end up in the appstream that was published on flathub.

**Comment by jgarciao** [comment]
I can add the ability to parse localized screenshots to the repo-to-webapp import process. But as Roddy said, the flathub appstream doesn't seem to have this info:

```
<screenshots>
<screenshot type="default">
<image type="source">https://raw.githubusercontent.com/endlessm/eos-photos/master/data/assets/screenshot1-es.png</image>
<image type="thumbnail" height="351" width="624">https://flathub.org/repo/screenshots/com.endlessm.photos-stable/624x351/com.endlessm.photos-4ba1969595153deb52d30027a2287df5.png</image>
<image type="thumbnail" height="702" width="1248">https://flathub.org/repo/screenshots/com.endlessm.photos-stable/1248x702/com.endlessm.photos-4ba1969595153deb52d30027a2287df5.png</image>
<image type="thumbnail" height="63" width="112">https://flathub.org/repo/screenshots/com.endlessm.photos-stable/112x63/com.endlessm.photos-4ba1969595153deb52d30027a2287df5.png</image>
<image type="thumbnail" height="126" width="224">https://flathub.org/repo/screenshots/com.endlessm.photos-stable/224x126/com.endlessm.photos-4ba1969595153deb52d30027a2287df5.png</image>
<image type="thumbnail" height="423" width="752">https://flathub.org/repo/screenshots/com.endlessm.photos-stable/752x423/com.endlessm.photos-4ba1969595153deb52d30027a2287df5.png</image>
<image type="thumbnail" height="846" width="1504">https://flathub.org/repo/screenshots/com.endlessm.photos-stable/1504x846/com.endlessm.photos-4ba1969595153deb52d30027a2287df5.png</image>
</screenshot>
... 
</screenshots>
```

**Comment by ahayzen** [comment]
FYI @AsciiWolf (*) has also pointed out on IRC that the changelog info needs to only show the correct locale, eg GIMP is showing multiple languages https://flathub.org/apps/details/org.gimp.GIMP

* Sorry IRC/matrix has gone all wonky so couldn't respond, i think this is the related issue.

**Comment by nedrichards** [comment]
Right - I believe we need an issue in appstream-glib to cover this, which I've just filed: https://github.com/hughsie/appstream-glib/issues/244

**Comment by jgarciao** [comment]
I think the new version of the backend will properly handle screenshot translations once they are informed in flathub's appstream file.

The GIMP release-info bug with the translations is also fixed: https://flathub.org/apps/details/org.gimp.GIMP
