### ISSUE TITLE
Add RSS Feed for Newly Published app and Newly Updated app

### ISSUE THREAD

**Issue by jgarciao** [flathub/linux-store-frontend#129]
It could be useful to have a RSS feed for the app collections, specially for the "New & Updated Apps"

**Comment by hadess** [comment]
> There is now a feed for New Apps: https://flathub.org/api/v1/apps/collection/new/feed.xml

Any chance to have more than just 4 items in the feed, or will it grow longer as items are added?

**Comment by bam80** [comment]
I wish also [Web Push](https://en.wikipedia.org/wiki/Push_technology#Webpush) and maybe others [Push technology](https://en.wikipedia.org/wiki/Push_technology) to be implemented

**Comment by jgarciao** [comment]
The feed is now showing the apps added in the last 7 days. I will probably change it to 15 days, as there are not many right now. Is updated dynamically, so new apps will appear.

**Comment by bam80** [comment]
> I might add a twitter/mastodon bot

I don't use both, that is why Web Push was proposed :)

**Comment by jgarciao** [comment]
Now we have 2 RSS Feeds:
- New Apps: 
  - Applications published in Flathub in the last 30 days
  - https://flathub.org/api/v1/apps/collection/new/feed
- Updated Apps:
  - Applications published or updated in Flathub in the last 7 days
  - https://flathub.org/api/v1/apps/collection/recently-updated/feed

Note that I have removed the .xml at the end of the url (still works with it, but it's not advertised) and now they are RSS 2.0 instead of Atom (this way the feed validated in W3C feed validator)

There is a new page with RSS feeds info that  will be published after fixing a couple of typos:
http://45.55.104.129/feeds

**Comment by jgarciao** [comment]
Yesterday I found a bug with the sorting of the RSS entries. I've fixed it and it will be deploy in production this week
