### ISSUE TITLE
Flathub's Website always display "Updated" date a day off

### ISSUE THREAD

**Issue by x80486** [flathub/linux-store-frontend#131]
I'm posting this one here, because the JSON response that I see has the correct date (not sure about the offset):

```json
{
  "flatpakAppId":"com.syntevo.SmartGit",
  . . .
  "currentReleaseVersion":"18.1.4",
  "currentReleaseDate":"2018-07-19T00:00:00.000Z",
  . . .
}
```

![screenshot from 2018-08-27 23-43-03](https://user-images.githubusercontent.com/34633617/44699627-1ec47880-aa53-11e8-8da4-7af4e6097a5f.png)

The correct release/update date is `2018-07-19` – what's coming back in the JSON response, but `app.model.ts::currentReleaseDate` is a `Date`, so it will be always one day off unless the offset is taken into consideration.

I think sending a date, instead of a timestamp, will do it here.

Not a big deal...just a minor detail :wink:

**Comment by jgarciao** [comment]
Thanks for reporting it. I'll take a look

**Comment by jgarciao** [comment]
In my computer (I live in Spain, which is GMT+1) the date is July 19, 2018.

Could be that you live in America (GMT - something)? If that is true I
think the date shown in Flathub is correct, because

2018-07-19T00:00:00.000Z (this is UTC time) is still July 18 in your continent.

**Comment by x80486** [comment]
I think what I was trying to say is that, you wouldn't need to account for the time part to display (or state) that a given event happended a certain day.

If that's OK, you close this one. Again, it's not a show stopper.
