### ISSUE TITLE
search should search in description too

### ISSUE THREAD

**Issue by albert-astals-cid-kdab** [flathub/linux-store-frontend#137]
Searching for pdf doesn't give me Okular nor evince, which means i'm not getting the answers i really want.

**Comment by TingPing** [comment]
Related to #123

**Comment by i-need-to-tell-you-something** [comment]
Mentioned in #50

**Comment by hfiguiere** [comment]
Searching for "video" doesn't show Pitivi.

**Comment by barthalion** [comment]
It does now, although at the very bottom of the results. We will be tuning how search works but that's technically fixed on the infrastructure's end/.
