### ISSUE TITLE
License: 'Free' is ambiguous

### ISSUE THREAD

**Issue by knocte** [flathub/linux-store-frontend#143]
Even if flatpak provides better sandboxing capabilities than previous package management systems in Linux, I want to know if the software I'm installing is opensource or not.

When the "License" field contains "Free", this is clearly ambiguous, because what does this exactly mean? Free as in beer (free-ware) or free as in freedom(FLOSS)? Please make this explicit. A way to do this would be to mention the specific name of the license. Or if this is too technical, just mention if the licence is approved by the OSI or FSF.

One example where this is not explicit: https://flathub.org/apps/details/org.gimp.GIMP

**Comment by allanday** [comment]
This is what it looks like in GNOME:

![image](https://user-images.githubusercontent.com/213068/47216228-242ba880-d39c-11e8-991e-f90d9bdc6851.png)

**Comment by knocte** [comment]
Great! no bug there. I guess we need a tooltip in the website.

**Comment by allanday** [comment]
> I guess we need a tooltip in the website.

It's shown on click, for what it's worth.

**Comment by knocte** [comment]
> It's shown on click, for what it's worth.

I guess you mean in Gnome. Yeah, on click or via tooltip, either way would be great to show in the website.

**Comment by jeremiah** [comment]
![screenshot_2018-12-19 gnu image manipulation program linux apps on flathub](https://user-images.githubusercontent.com/5260/50235267-7f225180-0385-11e9-840e-eef01057d3bf.png)

This is what it looks like on Clear Linux using Firefox. No tool tip when hovering.

**Comment by jgarciao** [comment]
It not implemented (yet)

**Comment by jgarciao** [comment]
Fixed in master. You can test it in the dev server

This is how it works now:

- Proprietary Apps: just show Proprietary  (example: [Spotify](http://45.55.104.129/apps/details/com.spotify.Client))
- Open source apps with short license value: show the license(s)  (example: [GIMP](http://45.55.104.129/apps/details/org.gimp.GIMP))
- Open source apps with long license value: show dialog (example: [Darktable](http://45.55.104.129/apps/details/org.darktable.Darktable))

**Comment by jeremiah** [comment]
This is great. I think the specificity of the license in the 'license' field helps visitors to flathub identify exactly what type of license the software has *before* they download it.
