### ISSUE TITLE
ADD : Ability to request for a flatpak of our favorite linux apps !

### ISSUE THREAD

**Issue by aiamuzz** [flathub/linux-store-frontend#147]
Now that we have a separate repo created for 'linux-store-frontend' ... i guess its time to add this here ...

Would be nice to have a section on this store with the ability to add a request for a flatpak of our favorite linux apps with an option for other users/community to vote on the same !

**Comment by TingPing** [comment]
I think this is also beyond the scope of the website.

**Comment by aiamuzz** [comment]
I am really confused ... If one has to request for flatpak app of their favorite linux app ... shouldn't such a section be accomodated on the flathub store website or store application ?

If not here ... where should such a request be posted ?

**Comment by TingPing** [comment]
I do not believe https://flathub.org should become a forum, which is effectively what this proposes.

I do not believe anywhere on Flathub should become that.

**Comment by aiamuzz** [comment]
> I do not believe https://flathub.org should become a forum, which is effectively what this proposes on this repo.
> 
> I do not believe anywhere on Flathub should become that.

what can i say ... one can see only as far as their understanding enables them !!!

a forum ... really ?

honestly I never thought even in my wildest imaginations that flathub should end up as one when i went on to make that suggestion ... yet all you could see and imagine is that flathub would turn into a forum ... that proves the need for discussion ... and for all you could do ... you closed this thread ...

if i let it at that ... you would have thought you nipped this in the bud from becoming a forum ... and you could have never been more wrong !!!

Even if we did create a 'Request for app' section ... it will be a moderated list with the ability to ONLY UP VOTE against an app entry already suggested by someone before or at the most admit one as a first time new request/entry ... how in the world could it end up as a forum ... tell me ... at the most it would be list recording voting stats ... NOTHING MORE !!!

**Comment by aiamuzz** [comment]
here is what i can volunteer for ... If you and the team feels that they can add be as a member to your team ... I am a creative guy by profession (a freelance designer) ... a graduate in computer science 15 years ago ... someone who missed the bus to becoming a coder/programmer ... 

so i can take the onus of discussing things with individuals to clarity on their suggestions of the non-technical nature(for the technical kind you people are already here) ... suggestions around processes and systems that will enable and enrich the flow of things ... bring additional value to things around here

Being an ex banker ... you can say i have more than a fair idea on the importance of processes and systems and their ability to make things more efficient.

so you people can assign me those tickets which you may not have time to discuss and deliberate or may not understand something for the potential they may have going forward ... i would be happy indulge and engage with the people suggesting things around here !
