### ISSUE TITLE
ADD : Ability for upstream to request volunteers to maintain their flatpak versions !!!

### ISSUE THREAD

**Issue by aiamuzz** [flathub/linux-store-frontend#148]
It would be really nice to have a section on this store where upstream's who are short of resources can ... **request for flatpak maintainers to package their apps to be added to the store**

I certainly know of one such upstream with a slew of great applications but are thin on resources ... but are  open to providing assistance to a 3rd party maintainer/packager ... as posted [HERE](https://github.com/flathub/flathub/issues/596)

**Comment by TingPing** [comment]
I fail to see how this is within scope of the website...

**Comment by barthalion** [comment]
There are few "third party" maintainers like @Alexander-Wilms and @bilelmoussaoui who could be interested, you can also just ask on IRC. We don't want requests here because we consider all applications "wanted" so it's matter of interest of upstream or downstream packagers.

**Comment by bilelmoussaoui** [comment]
The issue with Deepin apps is that they need a proper runtime or at least a baseApp. As I don't follow the Deepin dev closely I have no idea what they use and what not. If there are any specific app requests, you can always ping me and I will see what I can do when I have some free time to kill.

**Comment by aiamuzz** [comment]
@barthalion ... thanks for talking the time to at least present an argument !!!

You need to understand that when one takes time to suggest / share a feature request ... he would be doing with a macro intention ... its not about how 'I' can get something done ... if that was the case your suggestion to contact @Alexander-Wilms ... and ... @**bilelmoussaoui** ... is bang on !



**Consider this scenario/workflow ...** (around the suggestion i have raised here which unfortunately have been shutdown due to lack of seeing the macro picture behind the same !!!)

after installing flatpak at the CLI ... Flathub is the de facto face of 'Flatpak project' ... the single and only point of entry ... its frontend !!!

users come here looking for apps ...

1. they find something they like ... they install ...
2. they don't find something but really want it ... (no avenue to address this scenario)

Now imagine Upstream Devs ... they already have successful linux apps for their supported distro's

We the flatpak project ... our success is determined by the number of users who adopt it, use it, like it , refer others to use it ... and we grow ... our ultimate goal ... every project's ultimate goal !!!

@barthalion  ...  like you rightly said 'ALL APPLICATIONS ARE/have to be of the 'WANTED' TAG !!! ... hence my thread to be more [encouraging](https://github.com/flathub/linux-store-frontend/issues/150) (again shutdown) ... 
_**remember attitude is everything ... with the right kind you propel something high in the sky ... with the wrong kind you drive something into the ground**_

many linux dev's may not know of the flatpak system at all ... some may know but don't know if they need to dig deeper to find out ... we know there is BIG incentive in the concept of Flatpak ... but these Dev's who are already satisfied with their linux apps may not have the resources or aren't sold to this idea, or may simple not know it exists ... this GREAT concept ... what we are doing ... NOTHING !!!

Now If the above ... **user scenario 2** ... which has been wasted(for the lack of an avenue to address it was) on the Flathub store website ... was to suddenly start hosting a section where he/she could just raise a 'Request for App' ... the subsequent user's are provided with an option to up vote the favorite app already present there ...

We have ended up creating a completely 'alive system' ... one that could be cited to the upstream devs of those apps ... the upstream may still not be interested ... 

In the meantime ... this same 'Request for Apps' section along with our 'encouraging attitude' towards 3rd party maintainers ... will enable volunteers to take on these requested apps ... at least until the upstream are sold to the idea of participating in it themselves ...

Now Imagine we also have created a system where the install / usage app stat data(for unofficially maintained apps) is displaed ... one hand and  ... users 'requests for app vote count' ... on the other hand 
... Wont these numbers improve our chances of getting the upstream to turn ... to make the cut to officially supporting their apps ???

**Until this point ... the 'encouraging attitude' from the current 'discouraging' one ... is all that could make the difference**

If i was to really manage and drive this whole ecosystem ...
I would look forward to volunteers ... 3rd party maintainers (college under grad individuals or freshly graduated individuals) to help me build the above data ... the numbers to get upstream to involve to participate officially.

End result an increase in our 'Officially supported app count' on our store ... our other objective a pretty important one at that ... which will enable timely updates directly from the upstream devs and better response times to issues and their resolution !!!
;
;
;
Again i may be an upstream with limited resources ... i have a section on the flathub store (remember flathub is the ONLY face for flatpak  where i can request for volunteers to help maintain / package flatpaks for ME ...

now Imagin this section of 'Request for maintainers/packagers' on flathub ... along with the section 'Requests for apps' will be the feeding points for volunteers who are willing to adopt apps and maintain it for us ... in the eventuality that some app loses its 3rd party maintainer ... that app can go back on the adoption list another list for orphaned apps ... and this section too will serve as feeding point for volunteers to adopt and continue maintaining them !

so you see how these various sections/systems/ processes ... call it whatever you want ... it helps drive our ultimate goal ... INCREASE APPS ON FLATHUB ... ENABLE and INCREASE USE OF FLATPAK APPS ... ENABLE AND INCREASE 'OFFICIALLY SUPPORTED APPS' ... 

ALL BY just creating this separate sections no the Flathub store website !!!

I believe in this concept of Flatpak ... hence i am persistent ... some members out of haste call it spamming ... well what can one say to ... other than ... that they are myopic views !!!

SO IF THE TEAM SEES WHAT I AM TRYING TO SHOW ... THEN IT CERTAINLY A WIN-WIN FOR EVERYONE !!!
