### ISSUE TITLE
Encourage instead of discouraging 3rd party flatpak maintainers !!!

### ISSUE THREAD

**Issue by aiamuzz** [flathub/linux-store-frontend#150]
reply to ... [THIS](https://github.com/flatpak/flatpak/issues/2281#issuecomment-434315945) 

> I'm not sure there is much purpose to that though as it still allows third party maintainers it just discourages it over upstream maintainers

current reason provided for discouraging 3rd party maintainers ...

**I remember one of the flatpak/flathub team members giving the reason behind discouraging third party maintainers and preferring direct upstream involvement as saying that a 'third party' could drop out or go missing at any moment and their maintained app would get orphaned !!!** 

Here is what i was thinking ...

Flatpak/Flathub should go all out and encourage anybody and everybody to maintain apps for us(flatpak/flathub) ... let the fear of dropping(if that's really the official reason) out not worry us anymore ... 

Ways to encourage upstream involvement ...

Get the third party maintainer who has come forward with a request to add and INSIST him/her **to fire away a FORMAL mail/message/ping to upstream seeking their participation to add/maintain their app as a flatpak**, ... **this could serve as an unofficial message from flatpak/flathub** ... an introduction of the concept of flatpak and an unofficial invite of sorts ... after this is done ...

**differentiate no further ... go all out and encourage/assist the third party maintainer with the same fervor as an upstream maintainer would be extended support on the exercise of adding an app to our flatpak store.**

Besides the initial mail/message/ping to upstream through the volunteer maintainer at the beginning of the add pull request ... and information from ... [Request for apps Section](https://github.com/flathub/linux-store-frontend/issues/147) ... [Install/Usage Count on unofficial apps page](https://github.com/flathub/linux-store-frontend/issues/149) ... will enable the user community to get upstream to act on participating officially.

A more positive and organic approach of developing the community and ecosystem around our project and increase its use ... **instead of the current 'discouraging'  of volunteer 3rd party app maintainers.**

**Comment by TingPing** [comment]
Ok again you are bringing this up in the wrong place, don't spam issues everywhere. This is the place to discuss website improvements not package policies.

**Comment by aiamuzz** [comment]
what is this remark about 'spamming' ... its not appreciated !!!

I don't know if you agree ... may not be comparable to the coders efforts ... but it does take 'efforts' nevertheless ... to take time out and raise concerns ... provide feedback ... file and report bugs ... follow up on them ... suggest changes and request features ... assist fellow community on issues we may be aware of ...

FYI I AM NOT SPAMMING ... i have a genuine feedback to help improve the system ... and i am just going about finding the right place to do so 

**As per your own words you said that the team 'discourages' 3rd party initiations ... so this thread is an effort to address that attitude ...** 

originally i had posted this concern ...  at the flatpak repo ... now i am confused as to the right place to speak about this concern ... Is this the right place ? ... https://github.com/flathub/flathub/issues  ... 

If you don't like the concern spoken / expressed here ... all you have to do is counter it with your position and close it ... if your counter arguement makes sense we happily accept or we try some more and discuss to get our point across ...

labeling or calling names such as spamming and getting irritated about the efforts to raise it at the correct forum is not professional !!!

**Bugging or bothering the team unnecessarily is and never will be my intention !!!**

So you want the team and community to discuss the concern raised in this thread then point me to the right place so i can raise it there ... If you thing my concern's are nonsense ... then say so and close the issue !!!

PS : Encouraging is an attitude ... a virtue harnessed by successful managers everywhere ... a productive and inspiring one at that ... and the same should be done whole heartedly hence my efforts to address it ...

If you disagree and feel this thread addressing it is a waste of time ... try managing a team with a discouraging attitude vs an encouraging one and you'll see the difference yourself ... its very easy to be discouraging and dismissive !!!

This reply post an action ... with absolutely no intention of giving unsolicited advise ... but more of a reaction to the smell of a condescending attitude that may exist not consciously but sub consciously among coders ... a professional hazzard i guess !!!

**Comment by TingPing** [comment]
All I have to say is that there are effectively 3 Flathub reviewers all doing this in their free time and on a case by case basis we decide if a package is accepted and for the most part have not denied third party maintainers outside of some very high profile applications. From what I read you are not actually proposing any meaningful change in policy.

The most effective way for Flathub to continue growth is not by taking the limited time these reviewers have and moving them to becoming forum moderators nor by posting paragraph long issue reports on unrelated issue trackers.

I do appreciate your enthusiasm for Flathub but I am unsure that these issues result in any productive conversations. Your actionable comments like showing publisher information already had bug reports. Discussion on how that might appear can go there not in 4 new issues.

**Comment by aiamuzz** [comment]
@TingPing  ... i respect your time ... would appreciate the same ... nothing more nothing less ...

its all about getting the bigger picture ... I cannot give up on a concept i believe in ... so you could say i am persistent ... but a term such as 'spamming' is not acceptable ... You don't have to moderate ... just provide a rationale like you just did now ... 

Have you considered in the haste to close tickets you may just be missing out on things that could actually benefit ? ... i have not subscribed to the flatpak repository to fill my inbox with issues ... i read interesting ones ... pass on the technical ones ... and you know i find a lot of them have great suggestions yet have been shot down by you or the team ... i see potential in them ... but they are closed ... 

Anyways ... on the issues / requests i  created recently ...

If you really have time(not in haste please) ... its already a closed thread ... so you really want to see value on those suggestions to be accomodated on 'Flathub store Website' ... BTW most of them aren't mine but have already been requested here by someone else ..

Please read and tell me if those systems really don't help in anyway ...
https://github.com/flathub/linux-store-frontend/issues/148#issuecomment-434421222

**You can make the best of things ... but if you don't drive them ... market them well ... don't have a strategy to drive them ... then they are left wanting ... and eventually die** 

I don't know much ... havent really tried ... i am sure you are aware of a similar concept 'snaps' ... a similar sandboxed system like flatpak is what i have heard ... haven't heard it was creating any big waves from what i read.

If snapcraft.io is really their official app store then i literally counted and found less than 200 apps in total ( though the website claims thousands ... either they are hidden or i messed up something big time.)

And our Flathub store easily has more than 400 apps ... you'd know the count better !!!

I really like to see this spread far and wide ... hence the persistence and participation in my own capacity.
