### ISSUE TITLE
Add ChromeOS to the setup guide

### ISSUE THREAD

**Issue by jonathon-love** [flathub/linux-store-frontend#151]
from what i can gather, flatpaks can now be installed on chrome os v69+ !

would be fantastic if the setup guide could describe how to do this.

with thanks

**Comment by TingPing** [comment]
One problem is that Linux support is device dependent and I don't think Google maintains any official list of support.

**Comment by TingPing** [comment]
Also the setup guide is maintained here: https://github.com/flatpak/flatpak.github.io/blob/source/data/distro.yml

(Of course github adds transferring issues but you can't do it cross organisation..)

**Comment by jonathon-love** [comment]
i gather you wouldn't like to add a Chrome OS instructions that explains that only certain devices are supported?

this reddit sub is maintaining a list of supported devices: https://www.reddit.com/r/Crostini/wiki/getstarted/crostini-enabled-devices

**Comment by TingPing** [comment]
> i gather you wouldn't like to add a Chrome OS instructions that explains that only certain devices are supported?

I personally have nothing against it just a detail to mention.

**Comment by jonathon-love** [comment]
oh wait.

so would you be happy with me opening a PR adding Chrome OS instructions?

i thought you were opposed, but now i'm not so sure.

**Comment by TingPing** [comment]
Heh, I am not against you opening a PR. =)

**Comment by jonathon-love** [comment]
the issue is that i don't *have* a chromebook ... otherwise i'd be very happy to write install instructions for it :)
