### ISSUE TITLE
Licensing: adding a tooltip to "proprietary"

### ISSUE THREAD

**Issue by sanjayankur31** [flathub/linux-store-frontend#156]
Would it be possible to distinguish proprietary applications a little more by adding a tool tip that briefly explains how these are not free software, that they do not give the user the freedom to modify, share, and study? Gnome software does this, for example. 

Flatpaks are awesome and let us use proprietary software securely, but we still want to promote free software and increase awareness about it IMO?

**Comment by allanday** [comment]
I think this is already covered by https://github.com/flathub/linux-store-frontend/issues/143
