### ISSUE TITLE
Please use Matomo or another open source analytics software.

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/linux-store-frontend#162]
Since the purpose in #22 is to know about the website visitors, I believe [Matomo](https://matomo.org) would be a much better choice for users privacy and would remove our reliance on Google (which I think is bad for reasons that are probably obvious by now). 

It just makes sense to me for a free software project to use free software tools as opposed to proprietary tools.

(This would also affect #24 of course)

**Comment by jgarciao** [comment]
Thanks for your suggestion. Before adding Google Analytics I evaluated Matomo (formely Piwik):

Matomo's On-Premise: 
- PROs:
  - It's more privacy friendly as we host the data
- CONs:
  - We need to setup and maintain a http server with PHP7 enabled and a MySQL server
  - If we don't update properly the servers and the data is compromised it could be worse for the privacy of our users
  - In a nutsell, this option requires manpower to setup and properly maintain the service and also requires more server infrastructure

Matomo's Hosted solution: 
- PROs:
  - We don't have to manintain the servers. Better security than the On-Premises solution
  - It's not Google
- Matomo's Hosted solution CONs:
  - As we have more than 300.000 pageviews per month, we'll have to pay at least 49USD/month for the service
  - We are sharing the information with a 3rd party, so privacy lovers probably won't like it anyway

Given that flathub.org is a community project with little manpower and monetary resources, at this time I personally preffer to keep Google Analytics.

What we can do better is inform the users, adding a cookie consent bar, for example, or explaining in the privacy page how to configure the web browser to block trackers

**Comment by barthalion** [comment]
There's also [Fathom](https://github.com/usefathom/fathom/) which seems less resource hungry than Matomo and also respects users' privacy.

**Comment by lionirdeadman** [comment]
Well, I'd argue that privacy lovers might not like Matomo's hosted solutions as much as if we hosted it ourselves but the Matomo team is much more respectable than Google to most people.

The price though is.. yeah, an issue.

**Comment by lionirdeadman** [comment]
```What we can do better is inform the users, adding a cookie consent bar, for example, or explaining in the privacy page how to configure the web browser to block trackers```

Re-reading this, it's worth mentioning that such a solution would be *opt-out*, what we could do instead is having it be *opt-in* by only loading the google tracker if the person's accepted.

**Comment by barthalion** [comment]
@jgarciao I've got green light for using Matomo hosted by GNOME Foundation. Ping me on IRC when you're around, I will create an account for you.

**Comment by jgarciao** [comment]
@barthalion just gave me access to GNOME's Matomo. I'll be able to take a look and test it in July

**Comment by Zig-03** [comment]
> @barthalion just gave me access to GNOME's Matomo. I'll be able to take a look and test it in July

Please don't forget about removing other google trackers as well, such as googleusercontent.com.

**Comment by lionirdeadman** [comment]
> > @barthalion just gave me access to GNOME's Matomo. I'll be able to take a look and test it in July
> 
> Please don't forget about removing other google trackers as well, such as googleusercontent.com.

Googleusercontent is not a tracking source, it's an hosting service, I'm unsure why we use it only for certain images but that's another thing.

**Comment by yannicka** [comment]
There are commits to remove Google Analytics (like https://github.com/flathub/linux-store-frontend/commit/f6bcc61d53ae572f4bc89a5d8c3e75961241c0ad), but it's still there:

https://github.com/flathub/linux-store-frontend/blob/855e2cfcb464ac71ae2a905a3f6a615163665c89/src/index.html#L252-L267

What's the reason?

**Comment by TheEvilSkeleton** [comment]
Any updates here?

There is a closed MR, indicating that they switched to Matomo (https://github.com/flathub/linux-store-frontend/pull/186), but it still uses Google Analytics:

![image](https://user-images.githubusercontent.com/50847364/95926887-615c8280-0d8b-11eb-9791-d9e12a0dcafe.png)

There are minimal alternatives to Matomo in this website in case you're interested: https://developers.reverseeagle.org/replace/google-analytics/

P.S. ElementaryOS has switched to [Plausible Analytics](plausible.io/), and they love it!: https://blog.elementary.io/leaving-google-analytics-is-finally-plausible. Stats are publicly available as well: https://plausible.io/elementary.io

**Comment by jgarciao** [comment]
Dear Flathub users. I'm the one who added Google Analytics in the first place and now I'm removing it with PR #270. 

I'm sorry it took so long (a year since I added Matomo) but my involvement with this project has been very limited in the last couple of years for multiple reasons.

Thanks for contributing making flathub better with your suggestions. Happy 2021
