### ISSUE TITLE
Add MoinMoin syntax to badge page

### ISSUE THREAD

**Issue by hadess** [flathub/linux-store-frontend#166]
Took me a little bit to figure out so might be a good idea to have on the site. My version is at https://wiki.gnome.org/Apps/Books

For GIMP, as per the other example:
```
[[https://flathub.org/apps/details/org.gimp.GIMP|{{https://flathub.org/assets/badges/flathub-badge-en.png|Download on Flathub|width=240,align=middle}}]]
```

**Comment by jgarciao** [comment]
Thanks for the example. Is not in production yet but you can see it in the [demo server](http://45.55.104.129/badges)
