### ISSUE TITLE
quick setup: make sure to cover the most famous distros

### ISSUE THREAD

**Issue by tooomm** [flathub/linux-store-frontend#177]
https://distrowatch.com/index.php with it's ranking could be an indicator.

Flathub misses "Manjaro" and "MX Linux" top on their list for example!

**Comment by jgarciao** [comment]
You can contribute to the flatpak.org website to include installation instructions for any distro.

It's just sending a pull request like [Add Clear Linux OS setup instructions](https://github.com/flatpak/flatpak.github.io/pull/296) to the flatpak.github.io repository

Thanks for your contribution!
