### ISSUE TITLE
com.flashforge.FlashPrint missing icon

### ISSUE THREAD

**Issue by chadalen** [flathub/linux-store-frontend#179]
[https://flathub.org/apps/details/com.flashforge.FlashPrint](https://flathub.org/apps/details/com.flashforge.FlashPrint)

Icons you could use
![https://www.dream3d.co.uk/wp-content/uploads/2016/02/Flashforge-Icon.png](https://www.dream3d.co.uk/wp-content/uploads/2016/02/Flashforge-Icon.png)

![https://lh3.googleusercontent.com/-Zr7wR58mDws/VeqlCbH-PiI/AAAAAAAAADE/tqkkq_DZIQo/s400/256.png](https://lh3.googleusercontent.com/-Zr7wR58mDws/VeqlCbH-PiI/AAAAAAAAADE/tqkkq_DZIQo/s400/256.png)

**Comment by jgarciao** [comment]
Reported here too:  https://github.com/flathub/com.flashforge.FlashPrint/issues/1
