### ISSUE TITLE
Ubuntu setup needs short update

### ISSUE THREAD

**Issue by Eonfge** [flathub/linux-store-frontend#188]
The current tutorial on Ubuntu has fallen behind on reality. Problem is, that the repository version of Flatpak on Ubuntu is not kept well up to date. As such, the guide here needs updating:
https://flatpak.org/setup/Ubuntu/

## Proposed change
Drop the first bit that tells users on 18.10+ to install using the main repository.
The PPA from Alexander Larsson is the most reliable way for end users to get Flatpak updates.

It's almost as if Ubuntu has a competing platform

**Comment by jgarciao** [comment]
Sorry for the late answer but this issue should be filled here: https://github.com/flatpak/flatpak.github.io

I think @ahayzen maintains the flatpak in Ubuntu and he might know the best configuration
