### ISSUE TITLE
Search auto-focus and/or hotkey

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [flathub/linux-store-frontend#192]
This is a tiny feature request.

### Expected behavior

When landing [here](https://flathub.org/apps), it would be really nice if the UI focus of the browser would be initially set to the search box. This would invite more users to bookmark this page and quickly search for desired software even without using any external tools or browser plugins/addons/scripts.
Alternatively (or additionally) the site might support the hotkey ALT+SHIFT+F to focus on the search box. This is a feature present on Wikimedia sites as well as some other websites. Not ubiquitous by far yet, but still nice to have for those in the know. This feature usually goes along with a tooltip/alt-text to the search box which mentions the hotkey. See Wikipedia search box for reference.

In order to search something user has to:
1. Navigate to https://flathub.org/apps
2. Visually find search box
3. Place hand on mouse (unless already there)
4. Locate cursor (via moving the mouse)
5. Move cursor to search box
6. Left click on search box
7. Start typing

Steps 2-6 can be avoided by either of these features. First feature would presumably avoid these steps for slightly more users than feature 2 (search hotkey). 

### Observed on

- _URL:_ https://flathub.org/apps
- _Operating system:_ Linux (Kubuntu 18.04 LTS)
- _Browser:_ Firefox 70.0.1 (64-bit)

**Comment by Simon-Laux** [comment]
When clicking on the search icon I expect the appearing input field to be focused.
