### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by RasheedAZ** [flathub/linux-store-frontend#210]
Hi. If you guys think it's a good idea, can you include non-native apps and games that work perfectly on Linux in your online software centre, even if they're not open source?

For example, web based software/games that will run on any OS with a supported browser like Photopea and Jitsi Meet.

This way new users will be more open to adopting Linux based OS if their apps are truly cross-platform instead of bothering with Wine, etc.

Also, good proprietary software like for instance, I use Qoppa PDF Pro which is close to Adobe Acrobat in features that many workplaces cannot do without.

Also, closed source games with native Linux clients like War Thunder which runs on my Zorin 15 even without a graphics card.

The way it is now, these app stores and centres are all quite restrcitive and you simply can't find a place listing all software and games that can run on Linux.

**Comment by TingPing** [comment]
Flathub will accept most applications. This repo is for developing the website..
