### ISSUE TITLE
remove Google Analytics

### ISSUE THREAD

**Issue by kolokd** [flathub/linux-store-frontend#215]
only use matomo

**Comment by mobop** [comment]
@barthalion why this issue is closed without any information?

**Comment by bilelmoussaoui** [comment]
https://github.com/flathub/linux-store-frontend/commit/f6bcc61d53ae572f4bc89a5d8c3e75961241c0ad

**Comment by mobop** [comment]
@bilelmoussaoui , but currently deployed website has both of them. 
Google Analytics begins at view-source line 250

**Comment by bilelmoussaoui** [comment]
That's why the mentioned issue in the merge request wasn't closed

**Comment by jgarciao** [comment]
I'm reopening the issue because the user is correct. I left both Matomo and Analitycs active for a while to compare the results but now is time to remove Analytics

**Comment by kolokd** [comment]
what the hell are you all doing?
