### ISSUE TITLE
Process for changing an app-id?

### ISSUE THREAD

**Issue by aral** [flathub/linux-store-frontend#218]
Hi all,

Not sure where best to ask this but I need to change the app-id of Gnomit from ind.ie.Gnomit to org.small-tech.Gnomit (as we have moved from ind.ie to small-tech.org).

I haven’t been able to find any documentation on this so far.

Is there a suggested process? Things I need to watch out for, etc., or do I just go ahead, rename the repository and update all the app-ids in the app? 

Thanks in advance.

PS. Also, is there a preference as to whether the app-ids should be all lowercase or not (I’ve seen both). Is org.small-tech.gnomit preferable?

**Comment by TingPing** [comment]
This repo is about developing the website. Please just open a new MR to [flathub/flathub](https://github.com/flathub/flathub) with the new app-id, then you can mark the old one end of life.

**Comment by aral** [comment]
Thanks.
