### ISSUE TITLE
Real "Editor's Choice"

### ISSUE THREAD

**Issue by bertob** [flathub/linux-store-frontend#220]
It seems that currently "editor's choice" apps are determined by a [script](https://github.com/flathub/linux-store-frontend/blob/master/scripts/update-editors-choice-apps.sh) which looks at app ratings. That's a bit confusing, because the "editor's choice" implies that they're curated by a human editor/group of editors.

I'd suggest replacing the script with a hardcoded list of actual human-curated apps, which are rotated periodically (e.g. every month or so).

**Comment by barthalion** [comment]
It does not look at the ratings. The list is manually curated at https://github.com/flathub/linux-store-frontend/blob/master/scripts/update-editors-choice-apps-inputlist.

**Comment by bertob** [comment]
Oh sorry, should've checked more carefully :)

Looks like this file has only changed twice since 2018. Would you be open to changing it more often, to keep things fresh? I'd be happy to help with that.

**Comment by barthalion** [comment]
Absolutely, please submit a pull request and we'll take it from there.

**Comment by ITwrx** [comment]
I think proprietary applications should automatically be disqualified from being considered as Editor's Choice.

**Comment by jgarciao** [comment]
We discussed the Editor's list criteria at #69. The main problem is that different people with have different opinions and there is not an actual maintainer of this list.

As you saw, there have been very little changes for the last two years. We even thought about just removing this list and replace it in the front page for a Popular Games list based in download stats.

If you want to take care maintaining the Editor's list it's fine for me. This is what you have to do:
1. Edit https://github.com/flathub/linux-store-frontend/blob/master/scripts/update-editors-choice-apps-inputlist
2. Run [this script ](https://github.com/flathub/linux-store-frontend/blob/master/scripts/update-editors-choice-apps.sh)
3. The script will update [this file](https://github.com/flathub/linux-store-frontend/blob/master/src/app/shared/editors-choice-apps.ts)
4. Send a PR including the new version of the inputlist from point 1 and the updated file updated at point 3

The Editor's Choice games works the same way with update-editors-choice-games-inputlist and update-editors-choice-games.sh

Thanks for contributing to Flathub!

**Comment by bertob** [comment]
That sounds doable. I'd be happy to take over maintainership of the editor's choice list so it gets updated semi-regularly.

**Comment by bertob** [comment]
I think this can be closed since the editor's choice apps are being updated regularly now.
