### ISSUE TITLE
Angular version is outdated

### ISSUE THREAD

**Issue by itea-dev** [flathub/linux-store-frontend#253]
The app is currently on versión 6 of the Angular framework which is no longer supported.

https://angular.io/guide/releases

**Comment by itea-dev** [comment]
I can help you migrate to latest Angular version to take advantage of bug and security fixes and new improvements to the platform if you are open for merge requests.

**Comment by bilelmoussaoui** [comment]
Hey, thanks for your interest to help
I think the plan was to migrate from angular to next or nuxt, let me know if you're interested in helping on that part

**Comment by itea-dev** [comment]
Hi @bilelmoussaoui

I can help depending on the framework chosen. I'm more familiar with Angular and Vue.

Why do you plan a migration to another framework?

I think updating to latest Angular version will help to reduce bundle size and improve loading speed of the app and the developer experience without needing a migration to another framework.

**Comment by bilelmoussaoui** [comment]
Because most of the pages don't change much and having the pages server rendered makes more sense in our case.

**Comment by jgarciao** [comment]
Angular provides a tool to upgrade the version semi-automatically and, depending on the deprecated components the website might be using, it could take a couple of hours to update to Angular 10.  I also offer you my help if you are interested.

**Comment by itea-dev** [comment]
I have submitted a pull request which updates Angular to latest stable version until the app is migrated or server side rendered pages is implemented.
