### ISSUE TITLE
flathub: user tracking and respecting user privacy

### ISSUE THREAD

**Issue by okias** [flathub/linux-store-frontend#267]
Hello,

I noticed that when I'm on flathub, Firefox blocks by default 

Tracking:

- Google Analytics
- Browser-update.org (?)

Is this right place to ask, why Flathub
- [doesn't work without JS](https://github.com/flathub/linux-store-frontend/issues/219) (even over the fact it's very simple page I see) [8 months old issue],
- doesn't include [privacy policy page](https://github.com/flathub/linux-store-frontend/issues/24) [3 years old issue]
- didn't yet replaced [Google Analytics with Mamoto](https://github.com/flathub/linux-store-frontend/issues/162) or whatever else [already 2 years since the issue]

?

As we produce our software to respect users data and privacy, would be great, if platform as Flathub did the same.

**Comment by bilelmoussaoui** [comment]
> Hello,
> 
> I noticed that when I'm on flathub, Firefox blocks by default
> 
> Tracking:
> 
>     * Google Analytics
> 
>     * Browser-update.org (?)
> 
> 
> Is this right place to ask, why Flathub
> 
>     * [doesn't work without JS](https://github.com/flathub/linux-store-frontend/issues/219) (even over the fact it's very simple page I see) [8 months old issue],

Flathub will always require JS.

 
>     * doesn't include [privacy policy page](https://github.com/flathub/linux-store-frontend/issues/24) [3 years old issue]

Why duplicate the issue then?

>     * didn't yet replaced [Google Analytics with Mamoto](https://github.com/flathub/linux-store-frontend/issues/162) or whatever else [already 2 years since the issue]


Same here.

**Comment by okias** [comment]
Because it's like no-one gives attention to it. We (GNOME apps) should publish on Flathub, but it fails to provide even basic features (like privacy policy) to it's users. That's terrible.

**Comment by bilelmoussaoui** [comment]
Sure, it's an open source project and contributions are very much welcome. There's some [WIP thing](https://github.com/bilelmoussaoui/frontend) to replace the frontend with something better & does replace the Google Analytics with something else. 

Closing this one as it doesn't bring anything new, please leave a comment on those issues if you have anything to add or plan to contribute to the website itself

**Comment by okias** [comment]
@bilelmoussaoui have you considered reply to the JS issue and close it then, why you're so agile and closing this one?

**Comment by bilelmoussaoui** [comment]
Because this one is a duplicate :) I will have a look at the other issue

**Comment by bilelmoussaoui** [comment]
Google Analytics was removed in #270

**Comment by okias** [comment]
Also I noticed that Browser-update.org tracking warning disappeared.

**Thank you!**
