### ISSUE TITLE
Some apps have low resolution icons displayed

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/linux-store-frontend#272]
It appears that some apps recently started having low resolution (64x64) icons displayed on the [Flathub website](https://flathub.org) for some reason. These apps are for example [Firefox](https://flathub.org/apps/details/org.mozilla.firefox), [Thunderbird](https://flathub.org/apps/details/org.mozilla.Thunderbird) and [Minecraft Bedrock Launcher](https://flathub.org/apps/details/io.mrarm.mcpelauncher). Note that Minecraft Bedrock Launcher [uses](https://github.com/flathub/io.mrarm.mcpelauncher/blob/master/io.mrarm.mcpelauncher.json#L214) a svg icon.

**Comment by AsciiWolf** [comment]
Another apps where I noticed this issue are [jamovi](https://flathub.org/apps/details/org.jamovi.jamovi) and [ONLYOFFICE Desktop Editors](https://flathub.org/apps/details/org.onlyoffice.desktopeditors). The first app also seems to use a svg icon, however the second one has png icons.

**Comment by bilelmoussaoui** [comment]
The issue comes from using 64px icons instead of the 128px ones

**Comment by jgarciao** [comment]
I think is a regression of the new backend. I've filled an issue there and I'm closing this one
