### ISSUE TITLE
DLT Viewer not visible in flathub frontend

### ISSUE THREAD

**Issue by AlessandroBono** [flathub/linux-store-frontend#290]
The pull request https://github.com/flathub/flathub/pull/2147 have been merged for a while. However, the application is not present in the flathub frontend. https://flathub.org/apps/details/org.genivi.DLTViewer gives "App Not Found" to me. Note that the application is currently installable via command line with `flatpak install flathub org.genivi.DLTViewer`. There must be something that prevent DLT Viewer to show-up. I suspect a metainfo/metadata issue but it has been validated during the build process. Do you have any idea on how to track down this issue?

**Comment by jgarciao** [comment]
Is not showing up in the frontend because it doesn't appear in the appstream file (in your computer at /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml). After a  successful build the build bot adds the app info in this file of the repository and then is downloaded automatically in our computers when we run flatpak update.

A regular search doesn't find it:
```
$ flatpak update --appstream
$ flatpak search org.genivi.DLTViewer
No matches found
```

A remote-search does find it correctly:
```
$flatpak remote-info flathub org.genivi.DLTViewer
        ID: org.genivi.DLTViewer
       Ref: app/org.genivi.DLTViewer/x86_64/stable
      Arch: x86_64
    Branch: x86_64
Collection: org.flathub.Stable
  Download: 872,6 kB
 Installed: 2,0 MB
   Runtime: org.kde.Platform/x86_64/5.15
       Sdk: org.kde.Sdk/x86_64/5.15

    Commit: 8bbd3ed5bb520f366da8b4dd1c151f10940c76f5826d210918f76f7cbeed4c79
    Parent: 1caa57b65d222a542eb48a7adcbd79b17476b8b600110c600c8b94b9ca0bb5a6
   Subject: Manifest: Bump release 2.21.2 (2d2d7126)
      Date: 2021-03-25 11:51:50 +0000

```

Did you check the [build log](https://flathub.org/builds/#/builders/32/builds/41009)? Is it normal that it only builds in x86_64 and arm64 archs?

**Comment by AlessandroBono** [comment]
Hello, thanks for the feedback! The build log looks fine to me. I suspect we only have builds in x86_64 and arm64 because the kde runtime is present only for these architectures.

**Comment by bilelmoussaoui** [comment]
> Hello, thanks for the feedback! The build log looks fine to me. I suspect we only have builds in x86_64 and arm64 because the kde runtime is present only for these architectures.

Your issue comes probably from https://github.com/GENIVI/dlt-viewer/blob/0f0dbb49cec77fd1e7fe1a511e2d74ea3695cb57/src/src.pro#L64

the /usr isn't needed if you're already setting $PREFIX. You end up installing the desktop file in `/app/usr/share/applications` instead of `/app/share/applications`

**Comment by bilelmoussaoui** [comment]
The same thing for the icons.

**Comment by AlessandroBono** [comment]
> > Hello, thanks for the feedback! The build log looks fine to me. I suspect we only have builds in x86_64 and arm64 because the kde runtime is present only for these architectures.
> 
> Your issue comes probably from https://github.com/GENIVI/dlt-viewer/blob/0f0dbb49cec77fd1e7fe1a511e2d74ea3695cb57/src/src.pro#L64
> 
> the /usr isn't needed if you're already setting $PREFIX. You end up installing the desktop file in `/app/usr/share/applications` instead of `/app/share/applications`

Yes, hardcoding /usr isn't a good practice. I tried to get rid of it but I didn't know how to handle the path used for libqdlt. It uses a Qt-defined symbol that can't be changed and contains /usr. See https://github.com/flathub/flathub/pull/2147#discussion_r587832229. However, the Flatpak manifest as a workaround creates a symlink /app/share that points to /app/usr/share. See https://github.com/flathub/org.genivi.DLTViewer/blob/master/org.genivi.DLTViewer.yml#L24. Isn't it enough?

**Comment by AlessandroBono** [comment]
This has been fixed with https://github.com/flathub/org.genivi.DLTViewer/commit/10923e1179472e1d20684cb5a4ae038fde8c9eff
