### ISSUE TITLE
About the frontend json api?

### ISSUE THREAD

**Issue by Zaryob** [flathub/linux-store-frontend#292]
I'm planning to create a native application for flathub named fluthub. I'm on preliminary research for flathub.com

I got look at the codes of backend and recognize some of parts date pipe to get all relations for flathub.  I got that addresses from backend:

* for recently updated things: https://flathub.org/api/v1/apps/collection/recently-updated
* for look list of categories: https://flathub.org/api/v1/apps/categories
* for look list of apps in a specific category: https://flathub.org/api/v1/apps/category (For instance for education category: https://flathub.org/api/v1/apps/category/Education)
* for all apps: https://flathub.org/api/v1/apps
* for deatils of a app: for instance for AbacusActivity https://flathub.org/api/v1/apps/org.sugarlabs.AbacusActivity

After the create a desktop app with json data, then I gonna try to adapt it to install apps easily via this app. But from the first step i screwed up. Because I connot find json queries for that things:
* Popular Apps
* Editor's Choice Apps
* Editor's Choice Games

If I cannot find them all to adapt Discover, I just adapt CATEGORIES, then try to implement desktop app installation as well. 

Best regards.

**Comment by loganmarchione** [comment]
Not ideal, but would these work? I think these lists are updated manually first, then scripts run to update the site. 


Popular  
https://raw.githubusercontent.com/flathub/linux-store-frontend/master/scripts/update-popular-apps-inputlist


Editor's choice  
https://raw.githubusercontent.com/flathub/linux-store-frontend/master/scripts/update-editors-choice-apps-inputlist


Editor's choice games  
https://raw.githubusercontent.com/flathub/linux-store-frontend/master/scripts/update-editors-choice-games-inputlist
