### ISSUE TITLE
Internal Server Error for RSS feed

### ISSUE THREAD

**Issue by zroug** [flathub/linux-store-frontend#303]
Currently https://flathub.org/api/v1/apps/collection/new/feed results in a 500 Internal Server Error.

**Comment by zroug** [comment]
Seems to be fixed now. :+1:

**Comment by Arctize** [comment]
This is again the case again now, and has been for quite a few days.



The feed for updated apps on https://flathub.org/feeds works, but [the one for new apps](https://flathub.org/api/v1/apps/collection/new/feed) leads to an Internal Server Error.

**Comment by zroug** [comment]
The feed was fixed.
