### ISSUE TITLE
Support markdown in descriptions

### ISSUE THREAD

**Issue by Jacalz** [flathub/linux-store-frontend#323]
I use markdown in my metainfo file but it just shows up as literal text. It would be great if the store could support displaying the markdown instead.

https://flathub.org/apps/details/io.github.jacalz.rymdport

**Comment by razzeee** [comment]
I don't think that's valid for a description https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description

**Comment by Jacalz** [comment]
Ah, I see. Looks like I read ”some markup is supported” as meaning markdown.
