### ISSUE TITLE
URLs in RSS <link> tags result in a 404 error

### ISSUE THREAD

**Issue by scroggi** [flathub/linux-store-frontend#334]
The URLs provided in the `<link>` tags of both RSS update feeds (new apps, new and updated apps) result in a 404 error when followed.
- Current example: https://flathub.org/apps/io.github.cudatext.CudaText-Qt5

This could be due to a regression elsewhere in the site, or could be fixed by changing the URL format as follows:
- Corrected example: https://flathub.org/apps/details/io.github.cudatext.CudaText-Qt5

**Comment by razzeee** [comment]
https://github.com/flathub/website/pull/1043
