### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by jgarciao** [flathub/linux-store-frontend#50]
Right now searching _Gimp_ returns nothing because search only looks in name and summary fields. In this case the name is _GNU Image Manipulation Program_ and summary doesn't mention GIMP

- [ ] Quick fix: search also in flatpakappid
- [ ] Extendend fix: store keywords in the database and search also by keywords

**Comment by Alexander-Wilms** [comment]
Could this also cover the descriptions?

**Comment by jgarciao** [comment]
The webapp makes just one API request to get the app list and caches it for later use (for example for search): 

https://beta.flathub.org/api/v1/apps

The response doesn't include the description because the returned data was considerable bigger. I could make an API call to search for description, but I thing it will be slower

**Comment by Alexander-Wilms** [comment]
Makes sense. Could you search both, and show additional apps after the descriptions have been searched as well? I guess that would require deduplicating the results.
