### ISSUE TITLE
improve install hint placing

### ISSUE THREAD

**Issue by tooomm** [flathub/linux-store-frontend#75]
Moved from https://github.com/flathub/flathub.org/issues/54

>The install hint `Make sure to follow the setup guide before installing` placement could be improved within the app info pages for better visibility and logical structure:
>
> - On the right of the Install button or directly below it, not below the picture:
>![](https://user-images.githubusercontent.com/9874850/38417213-c9f4e8a2-3997-11e8-8ecd-2838c14e955a.png)
>
> - Above the instructions since a user has to check that first :)
>![](https://user-images.githubusercontent.com/9874850/38417218-cb5e4936-3997-11e8-9e0f-810efd4c31a4.png)

**Comment by allanday** [comment]
This might be obsoleted by #76, depending on who gets to which issue first.
