### ISSUE TITLE
Javascript files lack license information

### ISSUE THREAD

**Issue by Kasijjuf** [flathub/linux-store-frontend#78]
The JavaScript files for this application, as served by the web server -- specifically the files

[inline.af02cef26795ce2720fd.bundle.js](https://beta.flathub.org/inline.af02cef26795ce2720fd.bundle.js) ([archived](https://web.archive.org/web/20180408022649/https://beta.flathub.org/inline.af02cef26795ce2720fd.bundle.js))
[main.abf279d64d5d3ecbb14f.bundle.js](https://beta.flathub.org/main.abf279d64d5d3ecbb14f.bundle.js) ([archived](https://web.archive.org/web/20180408022659/https://beta.flathub.org/main.abf279d64d5d3ecbb14f.bundle.js))
[polyfills.b89f6da3f94d82c339a7.bundle.js](https://beta.flathub.org/polyfills.b89f6da3f94d82c339a7.bundle.js) ([archived](https://web.archive.org/web/20180408022707/https://beta.flathub.org/polyfills.b89f6da3f94d82c339a7.bundle.js))
[scripts.03e042f1f102bf0e2ed8.bundle.js](https://beta.flathub.org/scripts.03e042f1f102bf0e2ed8.bundle.js) ([archived](https://web.archive.org/web/20180408022711/https://beta.flathub.org/scripts.03e042f1f102bf0e2ed8.bundle.js))

do not contain any sort of license headers, nor do they direct the user to where unminified, unobfuscated corresponding sources for the files may be obtained.

**Comment by jgarciao** [comment]
Thanks for reaching out. Those javascript files are the result of the Angular "compilation" of the webapp. If you want to see the source code of this webapp is in this repo

If you are interested in debugging the webapp (and javascript) you can run it locally with npm start (see README file). This will compile the webapp in dev mode and all its javascript is unminified and unobfuscated

The license for all the components of the webapp are here https://flathub.org/3rdpartylicenses.txt
