### ISSUE TITLE
Search box looks terrible in WebKitGTK+

### ISSUE THREAD

**Issue by mcatanzaro** [flathub/linux-store-frontend#81]
Search box looks terrible in WebKitGTK+... I'll let the screenshot speak for itself:

![screenshot from 2018-04-08 22-27-39](https://user-images.githubusercontent.com/1424966/38478114-4c0ac966-3b7c-11e8-989b-24ab3c93a721.png)

If you think WebKit is doing something wrong, please let me know.

**Comment by mcatanzaro** [comment]
Thanks for the quick response!

Maybe since you used border: none outline: none,  WebKit should have tried to not draw the entry's frame. Prior to GTK+ 3.20 that would have just required omitting the call to `gtk_render_frame()`,  but nowadays everything uses gadgets and I'm not even sure if it's possible.

@carlosgcampos

**Comment by jgarciao** [comment]
Safari also shows the border
