### ISSUE TITLE
Webapp not loading properly in old versions of Firefox

### ISSUE THREAD

**Issue by jgarciao** [flathub/linux-store-frontend#82]
https://twitter.com/probonopd/status/982289421411102726?s=20

**Comment by splitt3r** [comment]
Anyway the es6 / es7 polyfills could help here.

**Comment by jgarciao** [comment]
I think this is the issue https://github.com/angular/angular-cli/issues/9340 
I still have to try the fix but I hope its fixable

**Comment by jgarciao** [comment]
This weekend I found time to investigate about this issue. As I wrote before this is a [known bug in Angular](https://github.com/angular/angular-cli/issues/9340) that is affecting Firefox 50 and older versions. 

The proposed workarounds are:

- Disable aot:
   - PROS: it's simple and it works
   - CONS: disabling aot makes the javascript bundle bigger (homepage goes from 656KB to 852KB) and page Load time is also worse (from 1.20 s to 2.29s)

- Hack to include an earlier versions of some dependencies tricking the system with a postinstall script: 
   - PROS: it works and bundle size and load time is not affected
   - CONS: it's an ugly hack that could make problems

I'm going to try solution 2 for a while (is already active in the [dev sever](http://45.55.104.129/home)) and add a warning to users with outdated browsers. In a few weeks (or before if there are regressions) I will disable the hack. In the end, Firefox users of versions < 52 are really few according to Google Analytics.

**Comment by jgarciao** [comment]
I'm sorry to say that after commiting this hack I merged a PR to update Angular to version 6 and the hack doesn't work any more :-(

As speed and performance is very important (see #21) and the amount of users affected by this bug is very low I'm not going to apply solution 1. I've added a warning to users of outdated browsers (you can test it in the [dev server](http://45.55.104.129/home))

If you want to update your browser without messing up the one that comes with your distro you can use flatpak for that:
- Install flatpak following the [setup guide](https://flatpak.org/setup/)
- Install Gnome Web or Eolie from flathub:
```
flatpak install flathub org.gnome.Epiphany
flatpak install flathub org.gnome.Eolie
```
- Another option is to install FirefoxNightly from [this repo](https://firefox-flatpak.mojefedora.cz/). I use it every day as my main browser
- I'm sure in the near future Chrome and other browsers will be also available at Flathub
