### ISSUE TITLE
the flathub button on flathub.org still says "Flathub Beta" although it is the non beta website

### ISSUE THREAD

**Issue by joergister** [flathub/linux-store-frontend#87]
I downloadet the svg and made a little change to it. You can find the modified version here
https://gist.github.com/joergister/8fa807242af904e8bb25236ce7b1843d#file-flathub-logo-toolbar-beta-svg

it's from  linux-store-frontend-master/src/assets/themes/flathub  in your project

sorry, i didn't already set up git on this machine, so this is not a pull request although it should be one. 
You can decide to use it, or to not use it, or to modify it a little more.

**Comment by TingPing** [comment]
It is still being worked on.

**Comment by joergister** [comment]
I know. Thats why I send this little fix.

**Comment by jgarciao** [comment]
What TingPing means is that we are still working on the website and that's why we kept the BETA label on the logo, even if the domain is flathub.org. There are some features we want to add and little bugs we want to fix before graduating it to non-beta.

Thanks for your contribution anyway!
