### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by splitt3r** [flathub/linux-store-frontend#91]
A copy button for the install command would be very nice just like:

![copy button](https://user-images.githubusercontent.com/1869584/39399384-f2f62b6c-4b1c-11e8-89a1-15bfe35cae3e.png)

**Comment by jgarciao** [comment]
Thanks to @antoniorsz we have a test version with this implemented in the [test server](http://45.55.104.129/apps/details/org.gimp.GIMP)

**Comment by jgarciao** [comment]
This is in production now
