### ISSUE TITLE
Spain translation on Flathub instead of English in Cow's Revenge

### ISSUE THREAD

**Issue by Zlopez** [flathub/linux-store-frontend#94]
Looking at the https://github.com/Dariasteam/Cows-Revenge/blob/master/linux_build/com.github.dariasteam.cowsrevenge.appdata.xml the file also contains English translation, but on the flathub page Spain translation is shown.

The same issue can be seen in Gnome Software.

Originally reported here: https://github.com/flathub/com.github.dariasteam.cowsrevenge/issues/3

**Comment by jgarciao** [comment]
I've answered in the original issue because I don't think the problem is here
